### PR TITLE
Add iso8601 formatter

### PR DESCRIPTION
**Pull request by coldeasy**
Added an `isoformat` function to allow formatting dates with a zulu extension rather than `+00:00` for UTC datetimes.

### CODE REVIEW

**Comment by jarondl** [comment]
Hi @coldeasy 
This is a well prepared PR, but I don't understand the premise.
The solution is a one-liner:

    dt.isoformat().replace('+00:00','Z')

So why would a user import dateutil for that?

**Comment by coldeasy** [comment]
@jarondl The main reason I am adding it here is to remove the need for this one-liner or indeed any 'wrapper' module that will does this due to the lack of extensibility of stdlib's `isoformat`.
Perhaps it's not worth it for such a small change right now but if there turns out to be other formatting features added to this library in future you could consider adding this.

**Comment by pganssle** [comment]
I'm tempted to close this because it's sat idle for over a year and I don't really want to introduce a whole new module just to format iso8601 strings, but if we do decide to go ahead with #18, I can see including this as an add-on module to that.

Either way, it'll need a rebase, but probably best to wait until it's more likely to be included. I don't foresee implementing #18 in 2.6.0.

**Comment by mariocj89** [comment]
Closing per https://github.com/dateutil/dateutil/pull/20#issuecomment-193942192. This is already substantially out of date and does not seem worth adding right now given this is a replacement for a one-liner.

**Pull request closed without merging**
