### PR TITLE
Updated tzinfo version.  Added version feature to zinfo file.

### PR DESCRIPTION
**Pull request by pganssle**
Added a ".version" file to the built tarball to fix Issue #27. This is accessible by `dateutil.zoneinfo.gettz_db_version()`. I believe that the way pytz does it they hard-code the version into the library, but I wanted to preserve the ability for users to use arbitrary zoneinfo_metadata when building dateutil themselves.

### CODE REVIEW

**Comment by jarondl** [comment]
Hi @pganssle , good work, but please don't merge yet. I have another idea I want to consider.

**Comment by pganssle** [comment]
@jarondl No problem. I marked this PR and the other two as 2.5.0 anyway, so I wasn't planning on merging them until after the 2.4.1 release, because they all add features rather than fix bugs.

This one especially I wanted to give a bit more time in terms of code review, because there are a lot of ways to do it. I really would have preferred to be able to infer the version from the tzfile itself, but I didn't see any obvious way to do that (there's a version in the MAKEFILE, but I checked old versions of the tzdata file and it wasn't always there, so I don't know if that's stable).

Anyway, I wasn't super happy with the elegance of this, so if you've got a better way to do it, I have zero problem with that.

**Comment by pganssle** [comment]
Superceded by #85

**Review by jjrauch32-lab — COMMENTED** [review]
k

**Pull request closed without merging**
