### PR TITLE
Fix tzwin error

### PR DESCRIPTION
**Pull request by pganssle**
This is a fix for #135. Very hard to write a test for this one. I have also refactored the timezone-related testing.

### CODE REVIEW

**Comment by pganssle** [comment]
Merging per @labrys's comments on #135. Will make a separate PR for #143.

**Comment by labrys** [comment]
Fairly busy lately but I'll test this when I get a chance.

**Comment by pganssle** [comment]
@labrys I think you already did test this in #135. Give it a bit, I'm going to try and fix the other tzwin issues.

**Comment by labrys** [comment]
Will do.  I had; was just going to confirm it. I'll wait though.

**Pull request merged**
