### PR TITLE
Fix timelex

### PR DESCRIPTION
**Pull request by ms-boom**
fix wrong tokens on unicode string

### CODE REVIEW

**Comment by pganssle** [comment]
I like where this is going, but I think we're actually losing some flexibility by enforcing `isalpha()` and `isdigit()`, etc. Right now, you can subclass `_timelex()` and override the relevant character sets, but in your version, that's no longer possible.

That said, I think that this *is* the right *default* approach. Today I'll make a PR against your branch with a suggested improvement.

**Comment by pganssle** [comment]
@jarondl This seems like a major change - any thoughts on the matter?

See also my PR at ms-boom/dateutil#1

**Comment by pganssle** [comment]
I'm going to go ahead and merge this. We can always undo it later if it causes some significant problems.

**Comment by jarondl** [comment]
Hi @pganssle, and @ms-boom,
a post-factum +1 from me. It is much better than what we had.

**Pull request merged**
