### PR TITLE
use heapq to improve performance

### PR DESCRIPTION
**Pull request by dekoza**
Patch based on [an article by Brian Beck](http://blog.brianbeck.com/post/22129050/speeding-up-dateutil-pythons-heapq-module-turns).

### CODE REVIEW

**Comment by pganssle** [comment]
This looks good. I'm going to just double check the profiling before I merge.

**Comment by jarondl** [comment]
Pretty cool.

**Comment by pganssle** [comment]
I tried to replicate this, but I don't have an rruleset that is slow at the sort step. I tried randomly generating one, but I'm not quite sure I know how to set the parameters of the randomization correctly. I shot @exogen (Brian Beck) an e-mail to see if he might be able to provide any insight.

That said, it doesn't seem to be significantly *worse* to use `heapq`, and it does conceptually make sense, so we can probably just accept this as is. Still, I'd like to track down whether the bottleneck has changed since 2007 or if I just don't have the right data set. I don't see anything obvious that would have changed.

Here are my results: [profiling](https://gist.github.com/pganssle/2572b41e57f9de3a8c9b), [code](https://gist.github.com/pganssle/c68277475bbe769f2c93).

**Comment by exogen** [comment]
Hi all! Been a while since I've seen this code.

You'll need a pretty big rruleset before you see any benefits from the patch. Here's an example one (which is exactly quite a bit smaller than the real ones I had before): https://gist.github.com/exogen/5e951c2e3d71cb2be8b4

(At the time, I was trying to create an rruleset for a bus schedule, and bus schedules aren't as simple as "every 15 minutes", but are published as fixed timetables – that's why I created each time in the timetable as a WEEKLY rrule. If I were to reimplement this today I'd probably avoid using an rruleset altogether and just implement the timetable lookup myself.)

Anyway, here's the time I get from that file with current dateutil:

```sh
$ time python rruleset.py 
2016-02-18 05:00:00

real    0m4.808s
user    0m4.727s
sys     0m0.063s
```

...and with this patch applied:

```sh
$ time python rruleset.py 
2016-02-18 05:00:00

real    0m0.576s
user    0m0.486s
sys     0m0.071s
```

The more rrules you have, the more valuable this patch becomes. Hope that helps! :)

**Comment by exogen** [comment]
I wonder if the initial calls to `rlist.sort` and `exlist.sort` are also unnecessary now? I don't think `heapq.heapify` needs the list to be initially sorted.

**Comment by pganssle** [comment]
@exogen Thanks so much for your help with this. With your code, I'm able to cleanly replicate this, so I am going to accept the PR.

@dekoza I think that Brian is right and `heapq.heapify` does not need the list to be initially sorted. I removed `rlist.sort` and `exlist.sort` and all the tests passed just fine. Do you want to make those changes and push another commit, or should I accept and make the changes myself?

**Comment by dekoza** [comment]
I'll do this, thanks.

**Comment by pganssle** [comment]
Brilliant. Merging! Thanks again @dekoza and @exogen

**Pull request merged**
