### PR TITLE
fixes #346: wrong addition of relativedelta

### LINKED ISSUE #346: wrong implementation of adding relativedelta's
Excerpt of `dateutil.relativedelta` for Python3.5, `dateutil==2.6.0`:

    def __add__(self, other):
        if isinstance(other, relativedelta):
            return self.__class__(years=other.years + self.years,
                                 ...
                                 hour=other.hour or self.hour,
                                 minute=other.minute or self.minute,
                                 second=other.second or self.second,
                                 ....

The problem is pretty simple: while for the plural version this might be correct, this is wrongly implemented for absolute minute/hour/second etc.

The problem is when `other.minute` is 0. That is, forcing the minute to be 0 cannot work. The default value is None for a reason :).

So instead of:

    minute=other.minute or self.minute,

it should be:
  
    minute=other.minute if other.minute is None else self.minute,

### PR DESCRIPTION
**Pull request by kootenpv**
testing `is not None` instead of truthiness

### CODE REVIEW

**Comment by pganssle** [comment]
Ah, yes, this seems like the right thing to do, good catch. Any chance you can add some test cases?

**Comment by kootenpv** [comment]
I rewrote some of my code as relativedelta, and my tests were not passing. Having installed this branch it was solved :)

I added some tests that should verify "AbsoluteAddition".

**Comment by kootenpv** [comment]
Is this going to be included?

**Comment by pganssle** [comment]
@kootenpv Sorry, haven't had much time to do `dateutil` stuff. I'll make sure to look at this tonight or tomorrow.

**Comment by pganssle** [comment]
LGTM.

**Comment by kootenpv** [comment]
Hey, I'm wondering what the release schedule will be? I'd like to depend again on the main branch rather than on my own :) Couldn't find information on the release cycles, that's why I ask :)

**Comment by pganssle** [comment]
@kootenpv I've been bad about that sort of thing, but I'll try to cut a release reasonably soon, want to get a few more bugfixes and such in first.

**Pull request merged**
