### PR TITLE
Updated the Readme.rst 

### PR DESCRIPTION
**Pull request by Satyabrat35**
## Summary of changes

The Readme.rst file now includes the Installation method  
PR for issue #778

### CODE REVIEW

**Comment by pganssle** [comment]
@Satyabrat35 Thank you for this contribution, can you please add yourself to the `AUTHORS.md` file? File is organized in alphabetical order by first name, and your name should have a `**D**` at the end, since you are contributing under a dual license (BSD + Apache 2.0).

**Comment by Satyabrat35** [comment]
Sure will do it!!!

**Comment by Satyabrat35** [comment]
The `AUTHORS.md` file has been updated
PR for issue #778

**Comment by pganssle** [comment]
@Satyabrat35 Thanks for your contribution!

**Pull request merged**
