### PR TITLE
avoid deprecated utcfromtimestamp

### LINKED ISSUE #1284: DeprecationWarning: datetime.utcfromtimestamp() is deprecated
With a self-built version of Python 3.12 that includes https://github.com/python/cpython/issues/103857:

```pycon
Python 3.12.0a7+ (heads/main-dirty:c527eb1c2a, May 15 2023, 10:39:28) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateutil.tz
/private/tmp/dateutil/src/dateutil/tz/tz.py:37: DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).
  EPOCH = datetime.datetime.utcfromtimestamp(0)
>>>
```

That warning again:

> DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).

This is from:

https://github.com/dateutil/dateutil/blob/b04edc08aa3559063b3b097f437941d8c4b84aba/src/dateutil/tz/tz.py#L37

### PR DESCRIPTION
**Pull request by graingert**
Fixes #1284

### CODE REVIEW

**Comment by graingert** [comment]
oh dear, CI is not looking healthy

**Comment by pganssle** [comment]
> oh dear, CI is not looking healthy

Yeah that's always the problem with this project (and most of the other low-velocity projects I have). Every time I try to make a change the CI has broken out from under me.

**Comment by graingert** [comment]
@pganssle fixed here https://github.com/dateutil/dateutil/pull/1286

**Comment by pganssle** [comment]
Thanks!

**Comment by wimglenn** [comment]
@pganssle  Can you push a release with this change to PyPI please?

**Comment by rafrafek** [comment]
I think the merged solution may be wrong. I think it should keep timezone-aware object, something like this:
```python
EPOCH = datetime.datetime.fromtimestamp(0, datetime.UTC)
```

**Pull request merged**
