### PR TITLE
Implement RFC2445, and make str(rrule) use it.

### LINKED ISSUE #47: Make str(rrule) to print the formatted RFC string.
Migrated launchpad issue [#1406305](https://bugs.launchpad.net/dateutil/+bug/1406305).

Quoting [Manuel Vazquez Acosta](https://launchpad.net/~mva-led):
>Sometimes (while interfacing with a DB, for instance) it is important to get the RFC string representation of a rrule. It would be great the the `str(rrule)` would work out-of-the-box.

He also suggested:
>Though I haven't fully test it, this may be a stating point: http://schinckel.net/2014/05/28/rrule-to-rfc-string/

### PR DESCRIPTION
**Pull request by schinckel**
Resolves #47.

This probably needs some tests. I'm getting test failures on master anyway though.

### CODE REVIEW

**Comment by pganssle** [comment]
@schinckel Thanks for doing this! For me, it's common to get 3 or 6 test failures in the time zone tests if I haven't built the tzinfo file, you don't have to worry so much about those tests unless you are making changes to the time zone related stuff. The PR is passing the travis and appveyor tests, though, so no problems on that front.

If you don't want to write tests, I can do so after the merge (which I'm thinking we should hold off on until after the upcoming 2.4.1 release), no problem.

**Comment by schinckel** [comment]
Yeah, I'm a bit busy with work at the moment.

**Comment by pganssle** [comment]
@schinckel No problem. After the 2.4.1 I can merge and I think it's probably best to refactor this so that it doesn't add the rfc2445.py module, but I don't mind doing all that. Thanks!

**Comment by pganssle** [comment]
Superceded by #62

**Pull request closed without merging**
