### PR TITLE
Fix ambiguous parse

### LINKED ISSUE #318: RFC822 timestamp using GMT is parsed into BST if local time is UK time
The following code snipped prints `True` unless the machine is using UK time.

```python
from datetime import datetime
from dateutil.parser import parse
from dateutil.tz import tzutc


d1 = datetime(2002, 10, 2, 13, 0, tzinfo=tzutc())
d2 = parse('Wed, 02 Oct 2002 13:00:00 GMT')
print(d1 == d2)
```

It appears that at [this point](https://github.com/dateutil/dateutil/blob/master/dateutil/parser.py#L605) in the parse function, the parser sees that local time is one of `('GMT', 'BST')` because in the Summer the UK uses BST (GMT+1).

Source issue: boto/botocore#1070

### PR DESCRIPTION
**Pull request by pganssle**
Should fix #318 in favor of #319. I don't 100% love special-casing UTC like this, but I think that's the only exception here and anything else would lead to even weirder edge cases.

### CODE REVIEW

**Comment by pganssle** [comment]
Ping @JordonPhillips

**Comment by pganssle** [comment]
@jbrockmendel Any thoughts?

**Comment by jbrockmendel** [comment]
Will look this over now; sorry it got lost in the inbox for a bit.

**Comment by jbrockmendel** [comment]
Not all that familiar with the `fold` method, need to do some reading on it.  But that aside, it looks like the point of this feature is to replace `tzinfo=tzlocal()` with `tzinfo=explicitly_named_tzinfo()`.

`_assign_tzname` could use a brief docstring, but it's a nice tight method.  +1

LGTM.

**Comment by pganssle** [comment]
@jbrockmendel Not quite. `fold` is an attribute for distinguishing between two otherwise identical dates, e.g. 1:30 AM EDT vs 1:30 AM EST during an EDT->EST transition. So:

`'2011-11-06T01:30 EDT'`
`'2011-11-06T01:30 EST'`

These two things are unambiguous representations (assuming you have the context to know that EST and EDT are both representations of the Eastern time zone) of the same naive datetime. With Python's time zone model, the tz offset is a function of the naive `datetime` portion, so for dates like the above differing only in their offset, there was no way to represent the difference with the same `tzinfo` object. In Python 3.6, they introduced `fold`, so you can represent those two, respectively, as:

`datetime(2011, 11, 6, 1, 30, fold=0, tzinfo=Eastern)`
`datetime(2011, 11, 6, 1, 30, fold=1, tzinfo=Eastern)`

In the old behavior, it used to be that we'd see `EST` or `EDT`, find that those were aliases for the local time zone name, and assign `tzlocal()`, but of course we didn't assign the `fold` component, because it didn't exist until recently. This patch just checks to see if the `tzname` doesn't match the string token but a datetime with `fold=1` set *would* match the string token, that we set `fold=1`.

**Comment by JordonPhillips** [comment]
Confirmed this works, thanks!

**Pull request merged**
