### PR TITLE
NEWS: convert to utf8, remove dos line endings

### PR DESCRIPTION
**Pull request by keszybz**
Makes it nicer to view in the terminal.

### CODE REVIEW

**Comment by pganssle** [comment]
I wonder why it even had dos line endings in the first place? I've been editing it on Linux.

**Comment by keszybz** [comment]
I think that most editors are smart enough to not display and preserve CRLF line endings.

**Comment by pganssle** [comment]
@jarondl Any thoughts on this? I don't think it matters that much, and the only reservation I have is that I think that on Windows, Notepad doesn't recognize LF as a linebreak at all, in which case it would become completely unreadable, whereas if I `cat` the file, it just doubles the linebreaks. Since most editors will figure it out either way, and the one common editor that's going to fuck it up will fuck it up *really badly* if we don't use DOS line endings, I'd say leave it DOS for just this file.

I'm fine with switching to UTF-8 encoding.

**Comment by labrys** [comment]
@pganssle Notepad will definitely go stupid without CRLF.

**Comment by keszybz** [comment]
I mostly care about the encoding, line-endings are less important.

**Comment by pganssle** [comment]
@keszybz OK, do you want to switch the line endings back to CRLF and I'll accept the PR?

Thanks for your contribution!

**Pull request merged**
