### PR TITLE
Remove Python 2.7 and Python <3.6 support.

### PR DESCRIPTION
**Pull request by Cabalist**
## Summary of changes

This deprecates Python 2.7 and Python <3.6.   These are no longer supported upstream and by removing them the code is simplified for it.   It also allows the possibility of using new language features that were previously Python 3 only.  (f-strings are really great) 

I use this library all the time and noticed it was the last thing in some of my projects that was bringing in `six`.    Let me know if any changes need to be made and thanks for all your hard work over the years.   This library has saved me A LOT of headaches.  :) 

 

### Pull Request Checklist
- [x] Changes have tests
- [x] Authors have been added to [AUTHORS.md](https://github.com/dateutil/dateutil/blob/master/AUTHORS.md)
- [x] News fragment added in changelog.d. See [CONTRIBUTING.md](https://github.com/dateutil/dateutil/blob/master/CONTRIBUTING.md#changelog) for details

### CODE REVIEW

**Comment by Cabalist** [comment]
Hmm... I might need some help on the travis failure above.  I can see that travisCI is pulling down https://dateutil.github.io/tzdata/tzdata/tzdata2020a.tar.gz and then seems to be unable to find `pacificnew` in the tarfile.   I can confirm it is there.    I will return to this after lunch.

**Comment by Cabalist** [comment]
What is the reason why this was closed?

**Comment by pganssle** [comment]
I did not want you to continue wasting your time on it and I don't have time to explain in depth right now.

We are way behind schedule in dropping Python 2, but there are changes that need to happen before then, and I am not interested in maintaining backports.

Thank you for your interest and enthusiasm, though.

**Comment by Cabalist** [comment]
No worries.  Is the "we" a private company or another project?   I can definitely help migrate if it is another OSS project. 

This PR is done except for something wonky with the external file it downloads.

**Pull request closed without merging**
