### PR TITLE
#623: added documentation for rrulestr function

### LINKED ISSUE #623: No documentation for rrulestr
There is apparently no documentation for `rrulestr`, just various examples, none of which explain the *many* arguments passed to it. This should be remedied ASAP.

### PR DESCRIPTION
**Pull request by prdickson**
## Summary of changes

Added doc string for _rrulestr
Reformatted docs for rrule module 

Closes #623 
### Pull Request Checklist
- [x] Authors have been added to [AUTHORS.md](https://github.com/dateutil/dateutil/blob/master/AUTHORS.md)
- [x] News fragment added in changelog.d. See [CONTRIBUTING.md](https://github.com/dateutil/dateutil/blob/master/CONTRIBUTING.md#changelog) for details

### CODE REVIEW

**Comment by pganssle** [comment]
@prdickson Same issue as #753 with your git commit metadata - do you want it updated so it shows up on github, or should I merge as-is?

**Comment by pganssle** [comment]
@prdickson It seems that you have not enabled maintainers to make edits on this branch, see [this link](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for more details. Can you enable that for this branch? I have some changes to the PR that I'd like to push to your PR.

**Comment by prdickson** [comment]
The allow edits from maintainers checkbox was already checked.  Not sure why you can't push changes to this PR.

**Comment by prdickson** [comment]
It would also be nice if these commits were associated with my github account.  Thanks.

**Pull request merged**
