### PR TITLE
add readthedocs badge, PyPi versions and license

### PR DESCRIPTION
**Pull request by gaborbernat**
see https://github.com/gaborbernat/dateutil/blob/badge/README.rst

### CODE REVIEW

**Comment by pganssle** [comment]
Hm.. License is not accurate because it's pulled from the PyPI metadata. Not a permanent situation, though.

**Comment by gaborbernat** [comment]
Yeah should self-fix once the PyPI one is fixed.

**Comment by gaborbernat** [comment]
@pganssle anything to do with this one?

**Comment by pganssle** [comment]
Hm... It's generally fine, but I'd like it if I could get the badges to be on two lines, rather than just overflowing from one line onto the next. I tried inserting an explicit linebreak and it looks quite ugly, unfortunately.

**Comment by gaborbernat** [comment]
@pganssle shall we close this then?

**Comment by pganssle** [comment]
@gaborbernat I'm going to keep it open a bit longer as a reminder to try and figure out how to do layout on RST so that we *can* include more badges without it looking messy.

**Comment by gaborbernat** [comment]
Fixed the merge conflict and gave it a go through a different approach :thinking: 

screenshot-github com-2018 03 29-13-09-27

The only other way would be putting it inside a table I think.

**Comment by pganssle** [comment]
@gaborbernat Yeah, that looks a lot better. Thanks for doing that.

**Pull request merged**
