### PR TITLE
Fix Easter typos

### PR DESCRIPTION
**Pull request by hugovk**
## Summary of changes

Easter is a proper noun. 

Fixes https://dateutil.readthedocs.io/en/stable/easter.html

### Pull Request Checklist
- [n/a] Changes have tests
- [x] Authors have been added to [AUTHORS.md](https://github.com/dateutil/dateutil/blob/master/AUTHORS.md)
- [n/a] News fragment added in changelog.d. See [CONTRIBUTING.md](https://github.com/dateutil/dateutil/blob/master/CONTRIBUTING.md#changelog) for details

### CODE REVIEW

**Comment by hugovk** [comment]
Yes, will include a fix for the numbered list formatting:

image

**Comment by ffe4** [comment]
Screen Shot 2020-04-04 at 16 05 04


Not sure I like this look is an improvement. Also, aren't these numbers supposed to represent the corresponding constant values, instead of just a numbered listing?

**Comment by hugovk** [comment]
That's the old look: https://dateutil.readthedocs.io/en/stable/easter.html

The new look will be more like:

image

**Comment by ffe4** [comment]
Sorry, I did just quickly copy-paste your code instead of pulling it via git and made a mistake. Your screenshot is correct.

**Comment by pganssle** [comment]
@ffe4 I think it might be a coincidence that the numbering happens to match the values. We could maybe rearrange things to use non-numbered bullets, or to have non-numbered bullet points that mention the constant directly, but for the purposes of this minor PR we can keep it as is and just fix the numbering.

**Comment by pganssle** [comment]
Appveyor status reporting is currently not working and there appears to be very little I can do about it, but the actual build is passing so I'm going to go ahead and merge.

I guess we can skip the news on this as it's pretty trivial.

**Pull request merged**
