### PR TITLE
move CI to tox

### PR DESCRIPTION
**Pull request by gaborbernat**

### CODE REVIEW

**Comment by gaborbernat** [comment]
Resolves #519.

**Comment by pganssle** [comment]
@gaborbernat Hrm.. This has a similar problem to one of my earlier configurations - tests are not covered. I thought we were going to set it up so that the regression was that we're not doing `changedir` anymore?

I'll figure it out later I guess.

**Comment by gaborbernat** [comment]
I explicitly excluded tests from coverage, I can enable it if you want?

**Comment by pganssle** [comment]
@gaborbernat Yes, I've caught several bugs when I realized that parts of my test suite was not getting executed.

**Comment by gaborbernat** [comment]
added back via config flag in ``tox.ini`` in #568 (yeah was lazy to create another PR for it, sorry)

**Pull request merged**
