### PR TITLE
Reduces appveyor tests

### PR DESCRIPTION
**Pull request by kirit93**
In relation to #529 

@gaborbernat please let me know if this is the correct approach.

### CODE REVIEW

**Comment by pganssle** [comment]
@kirit93 I think you may have branched from the wrong master - might be related to the fact that I rewrote your history. You may need to `git fetch upstream master; git reset --hard upstream/master` to get your local master in sync with the `dateutil` master.

**Comment by kirit93** [comment]
@pganssle Done, thanks.

**Comment by pganssle** [comment]
@kirit93 You don't have to make new PRs, and in fact it's better if you don't. If you just rewrite the history (`git commit --amend`) and force push to your PR branch, it will re-start the builds, and (more importantly), it will *stop all the runs you kicked off with the first branch*.

**Comment by kirit93** [comment]
Oh okay, sorry, I ended up deleted the old branch and created a new one with a new PR. Henceforth I'll keep this in mind and not create a new PR.

**Pull request closed without merging**
