### PR TITLE
Protect tzical cache with a lock (fixes #428)

### LINKED ISSUE #428: tzical is not thread-safe
```
Traceback (most recent call last):
...
  File "dateutil/tz/tz.py", line 1109, in utcoffset
    return self._find_comp(dt).tzoffsetto
  File "dateutil/tz/tz.py", line 1062, in _find_comp
    return self._cachecomp[self._cachedate.index((dt, self._fold(dt)))]
IndexError: list index out of range
```

``_cachedate`` and ``_cachecomp`` are not protected by a lock.

### PR DESCRIPTION
**Pull request by Unrud**

### CODE REVIEW

**Comment by pganssle** [comment]
Hm.. This isn't really how I want to fix this (I am planning on ripping out a lot of the cache stuff from `tzical` anyway and replacing it), but if we get close to a new release and I still haven't followed up on #342, I'll accept this.

**Comment by Unrud** [comment]
> Hm.. This isn't really how I want to fix this

This was meant as a provisional fix, until the rewrite is completed.

**Comment by pganssle** [comment]
@Unrud Yeah. I don't think we're going to do any more bugfix releases for the 2.6.0 branch, but if I don't fix caches before the 2.7.0 release I'll merge this.

**Comment by pganssle** [comment]
Actually, this has no changes to the public interface, so I can always just rip it out later if I need to change it. Doesn't hurt to merge it.

**Pull request merged**
