### PR TITLE
add Azure Pipelines

### PR DESCRIPTION
**Pull request by vtbassmatt**
## Summary of changes

Hi! I'm a product manager on Azure Pipelines. We've been helping a lot of Python projects move over to Azure Pipelines for continuous integration. There are a few key benefits we offer:
- Generous free allowance for open source projects - 10 jobs in parallel, plenty of minutes
- All 3 major platforms - Linux, macOS, and Windows - hosted in Azure
- Great test analytics giving you insight into pass/fail rates on tests over time

I'm hoping you'll give us a try! The easiest way to get started is to let azure-pipelines.yml land in master, then install the [Azure Pipelines app](https://github.com/marketplace/azure-pipelines). If that's a bit too much, you can install the app, let it put a dummy azure-pipelines.yml in a branch, then go in and try out the build against this PR's branch. Even even _that's_ too much, you can preview what the output looks like in the [demo pipeline I set up](https://dev.azure.com/mattc-demo/Test1/_build/results?buildId=988&_a=summary).

We offer GitHub Checks integration, build badges [Build Status](https://dev.azure.com/mattc-demo/Test1/_build/latest?definitionId=47&branchName=azure-pipelines), and all the other stuff you'd expect from a CI system. I didn't try to put those into this PR, since you'd want them to go against your actual Azure Pipelines organization rather than my demo.

### CODE REVIEW

**Comment by pganssle** [comment]
@vtbassmatt Thanks Matt! I was literally today considering adding an issue to do this, because I'll be mentoring a sprint this weekend. Of course, now the sprinters don't get to do it.

I'll look over this when I have a bit of time, but I appreciate that you've done this.

In case you were looking at doing the same thing for [setuptools](https://github.com/pypa/setuptools) please hold off until after this weekend, since I'd like to offer that as an option for the sprinters.

**Comment by pganssle** [comment]
@vtbassmatt Is there any way to test the azure pipelines out before landing it in master? I prefer to keep a clean history and if there are any bugs I'd like to fix them before merge.

If not, I'll just do the same thing I usually do when setting up new CI - land it in master on a fork and point the CI there until all the tests are passing.

**Comment by pganssle** [comment]
Er, sorry for the spam, actually I realize now that the demo pipeline is basically already my forked version.

One last question - is there no way for me to install the app as the `dateutil` org? The link you sent seems to be connected to my personal account, and I prefer to keep all permissions centralized through org access, so that "admin privileges on the github org" is sufficient to do everything.

**Comment by vtbassmatt** [comment]
Hey, sorry to rob your sprinters of an opportunity! I won't touch setuptools until next week, I promise :grin:

I was able to change from my personal account to an org account when I went to install the app:
image

**Comment by pganssle** [comment]
@vtbassmatt No worries about "robbing" the sprinters, it will actually probably be good that we're starting with a known-good template, because the `setuptools` sprinters can crib from it, and the `dateutil` sprinters can add new jobs like tests for #870.

I had two more questions:

1. Can you explain what [this commit](https://github.com/dateutil/dateutil/pull/868/commits/e6bf53fed469c4cf899d5c965b2edf45a44ae1b2) is fixing? What does "uploading test results" mean? I'm kinda curious because I would like to start [generating docs previews as part of the CI](https://github.com/pypa/setuptools/pull/1367), but Netlify requests way more permissions than I'm willing to give it.
2. I was able to install it as the org (not sure why this wasn't an option before), but it's asking me to log in to Microsoft Live. Does this mean that the permissions would necessarily be linked to my personal live account? I'd prefer to have the permissions linked to the org GH account instead.

I will hang out in the [gitter](https://gitter.im/dateutil/dateutil) in case you want to have a conversation about this in real time, or if you shoot me an e-mail with a phone number, I can call you and we can talk about it. Also, this contribution is already great as is, if you don't have time to go through this stuff with me just let me know and I can figure it out myself.

**Comment by vtbassmatt** [comment]
Jumping into the Gitter right now

**Comment by vtbassmatt** [comment]
📣

**Pull request merged**
